apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudassist-backend
  namespace: cloudassist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudassist-backend
  template:
    metadata:
      labels:
        app: cloudassist-backend
    spec:
      serviceAccountName: cloudassist-backend
      containers:
        - name: backend
          image: europe-west1-docker.pkg.dev/project-6bc48aee-fd23-426b-8c7/cloudassist/backend:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: cloudassist-backend
  namespace: cloudassist
spec:
  selector:
    app: cloudassist-backend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
